import React, { useState } from "react";
import Head from "next/head";
import { MenuIcon } from "@heroicons/react/outline";

import Header from "../components/Header";

export default function Home() {
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Header
          open={isDrawerOpen}
          drawerToggle={() => setIsDrawerOpen((preState) => !preState)}
          drawerHandler={
            <div className='absolute right-0 cursor-pointer'>
              <MenuIcon className='h-8' />
            </div>
          }
        />
      </main>
    </div>
  );
}
