import React, { useState } from "react";
import Head from "next/head";
import { MenuIcon, XIcon } from "@heroicons/react/outline";

import Header from "../components/Header";

export default function Home() {
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='relative'>
        <Header
          open={isDrawerOpen}
          drawerToggle={() => setIsDrawerOpen((preState) => !preState)}
          drawerHandler={
            <div className='absolute right-5 mt-5 cursor-pointer'>
              {!isDrawerOpen ? (
                <MenuIcon className='h-8 xl:hidden' />
              ) : (
                <XIcon className='h-8 xl:hidden' />
              )}
            </div>
          }
        />

        <div className='flex justify-center items-center h-full bg-red-400'>
          <h1>
            Hi, I am <span>Dhruvil Gajjar</span>
          </h1>
        </div>
      </main>
    </div>
  );
}
