import React from "react";
import Head from "next/head";
import { gql } from "@apollo/client";

import client from "../apolloClient";
import Title from "../components/Title";
import ProjectCard from "../components/ProjectCard";

const portfolio = ({ projects }) => {
  return (
    <>
      <Head>
        <title>Portfolio | Dhruvil Gajjar</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex'>
        <div className='flex flex-col xl:w-5/6 xl:px-10 px-4 pt-1 mb-10 xl:ml-1.6'>
          <Title title='PORTFOLIOS' />

          <div className='grid md:grid-cols-2 md:space-x-5 xl:grid-cols-3 xl:space-x-5'>
            {projects.map((project) => (
              <ProjectCard
                key={project.id}
                imageURL={project.projectImage.url}
                projectURL={project.projectURL}
                projectSourceCodeURL={project.projectSourceCode}
                projectTitle={project.projectName}
                projectDescription={project.projectDescription.text}
              />
            ))}
          </div>
        </div>
      </div>
    </>
  );
};

export default portfolio;

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query {
        projects {
          id
          projectName
          projectDescription {
            text
          }
          projectImage {
            url
          }
          projectURL
          projectSourceCode
        }
      }
    `,
  });

  const { projects } = data;

  return {
    props: {
      projects,
    },
  };
}
